### ISSUE TITLE
Captcha Solver does not work after python script conversion to exe

### ISSUE THREAD

**Issue by toptierprojections** [networkdynamics/pytok#11]
Hello,
I created a simple Python script using pytok, and it works perfectly in my local development environment. However, after converting it to an .exe file (which was challenging due to the Playwright dependency), I'm required to manually solve the TikTok captcha before the scraper begins working. Do you have any idea why this is happening?

Also, I had to install the TikTokApi module during the process—could there be any connection?

Thank you!

**Comment by bendavidsteel** [comment]
I recently had to switch to allow manual captcha solves due to improvements in the captcha (although I have a plan to get back on top of it). There's now a new kwarg in the constructor that flips between auto and manual captcha solves. I also added TikTokApi as a dependency because some of it's methods can be useful sometimes when the cookies are set correctly. So basically this is all because of a recent update from me! 

But I don't really have any experience with converting Python scripts to executables, so I won't really be able to help with this one. Sorry!
